// <auto-generated />
namespace GestionDeTurnos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class prueba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(prueba));
        
        string IMigrationMetadata.Id
        {
            get { return "201901191649122_prueba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
