insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('A.1','Ciclomotores hasta 50cc.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('A.2.1','Motocicletas (incluidos ciclomotores y triciclos) de hasta 150 cc de cilindrada.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('A.2.2','Motocicletas (incluidos ciclomotores y triciclos) de más de 150 cc y hasta 300 cc de cilindrada.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('A.3','Motocicletas (incluidos ciclomotores y triciclos) de más de 300 cc de cilindrada',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('A.4','Motocicletas (incluidos ciclomotores y triciclos) de cualquier cilindrada utilizados para el transporte comercial e industrial.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('B.1','Automóviles, utilitarios, camionetas y casas rodantes motorizadas hasta 3500 kg total.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('B.2','Automóviles y camionetas hasta 3.500 kg de peso con un acoplado de hasta 750 kg o casa rodante no motorizada.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('C','Camiones sin acoplado ni semiacoplado y casas rodantes motorizadas de más de 3.500 kg de peso y automotores comprendidos en la clase B1.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('D.1','Automotores del servicio de transporte de pasajeros de hasta 8 plazas y los comprendidos en la clase B.1.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('D.2','Vehículos del servicio de transporte de más de 8 pasajeros y los de las clases B, C y D.1;',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('D.3','Servicios de urgencia, emergencia y similares.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('E.1','Camiones articulados y/o con acoplado y los vehículos comprendidos en las clases B y C;',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('E.2','Maquinaria especial no agrícola.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('E.3','Vehículos afectados al transporte de cargas peligrosas.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('F','Automotores con la descripción de la adaptación que corresponda a la discapacidad de su titular.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('G.1','Tractores agrícolas.',1)							
insert into [dbo].[LicenseClasses] (Codigo,Descripcion,Enable) values ('G.2','Maquinaria especial agrícola.',1)							
