insert into Countries (Descripcion,Predeterminado) values ('AUSTRIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BELGICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BULGARIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CHIPRE',0);	
insert into Countries (Descripcion,Predeterminado) values ('DINAMARCA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ESPAÑA',0);	
insert into Countries (Descripcion,Predeterminado) values ('FINLANDIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('FRANCIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GRECIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('HUNGRIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('IRLANDA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ITALIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('LUXEMBURGO',0);	
insert into Countries (Descripcion,Predeterminado) values ('MALTA',0);	
insert into Countries (Descripcion,Predeterminado) values ('PAISES BAJOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('POLONIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('PORTUGAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('REINO UNIDO',0);	
insert into Countries (Descripcion,Predeterminado) values ('ALEMANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('RUMANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SUECIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('LETONIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ESTONIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('LITUANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('REPUBLICA CHECA',0);	
insert into Countries (Descripcion,Predeterminado) values ('REPUBLICA ESLOVACA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ESLOVENIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ALBANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLANDIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('LIECHTENSTEIN',0);	
insert into Countries (Descripcion,Predeterminado) values ('MONACO',0);	
insert into Countries (Descripcion,Predeterminado) values ('NORUEGA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ANDORRA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAN MARINO',0);	
insert into Countries (Descripcion,Predeterminado) values ('SANTA SEDE',0);	
insert into Countries (Descripcion,Predeterminado) values ('SUIZA',0);	
insert into Countries (Descripcion,Predeterminado) values ('UCRANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MOLDAVIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BELARUS',0);	
insert into Countries (Descripcion,Predeterminado) values ('GEORGIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BOSNIA Y HERZEGOVINA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CROACIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ARMENIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('RUSIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MACEDONIA ',0);	
insert into Countries (Descripcion,Predeterminado) values ('SERBIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MONTENEGRO',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUERNESEY',0);	
insert into Countries (Descripcion,Predeterminado) values ('SVALBARD Y JAN MAYEN',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS FEROE',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLA DE MAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('GIBRALTAR',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS DEL CANAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('JERSEY',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS ALAND',0);	
insert into Countries (Descripcion,Predeterminado) values ('TURQUIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BURKINA FASO',0);	
insert into Countries (Descripcion,Predeterminado) values ('ANGOLA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ARGELIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BENIN',0);	
insert into Countries (Descripcion,Predeterminado) values ('BOTSWANA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BURUNDI',0);	
insert into Countries (Descripcion,Predeterminado) values ('CABO VERDE',0);	
insert into Countries (Descripcion,Predeterminado) values ('CAMERUN',0);	
insert into Countries (Descripcion,Predeterminado) values ('COMORES',0);	
insert into Countries (Descripcion,Predeterminado) values ('CONGO',0);	
insert into Countries (Descripcion,Predeterminado) values ('COSTA DE MARFIL',0);	
insert into Countries (Descripcion,Predeterminado) values ('DJIBOUTI',0);	
insert into Countries (Descripcion,Predeterminado) values ('EGIPTO',0);	
insert into Countries (Descripcion,Predeterminado) values ('ETIOPIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GABON',0);	
insert into Countries (Descripcion,Predeterminado) values ('GAMBIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GHANA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUINEA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUINEA-BISSAU',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUINEA ECUATORIAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('KENIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('LESOTHO',0);	
insert into Countries (Descripcion,Predeterminado) values ('LIBERIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('LIBIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MADAGASCAR',0);	
insert into Countries (Descripcion,Predeterminado) values ('MALAWI',0);	
insert into Countries (Descripcion,Predeterminado) values ('MALI',0);	
insert into Countries (Descripcion,Predeterminado) values ('MARRUECOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('MAURICIO',0);	
insert into Countries (Descripcion,Predeterminado) values ('MAURITANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MOZAMBIQUE',0);	
insert into Countries (Descripcion,Predeterminado) values ('NAMIBIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('NIGER',0);	
insert into Countries (Descripcion,Predeterminado) values ('NIGERIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('REPUBLICA CENTROAFRICANA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SUDAFRICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('RUANDA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SANTO TOME Y PRINCIPE',0);	
insert into Countries (Descripcion,Predeterminado) values ('SENEGAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('SEYCHELLES',0);	
insert into Countries (Descripcion,Predeterminado) values ('SIERRA LEONA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SOMALIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SUDAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('SWAZILANDIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('TANZANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CHAD',0);	
insert into Countries (Descripcion,Predeterminado) values ('TOGO',0);	
insert into Countries (Descripcion,Predeterminado) values ('TUNEZ',0);	
insert into Countries (Descripcion,Predeterminado) values ('UGANDA',0);	
insert into Countries (Descripcion,Predeterminado) values ('REP.DEMOCRATICA DEL CONGO',0);	
insert into Countries (Descripcion,Predeterminado) values ('ZAMBIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ZIMBABWE',0);	
insert into Countries (Descripcion,Predeterminado) values ('ERITREA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SANTA HELENA',0);	
insert into Countries (Descripcion,Predeterminado) values ('REUNION',0);	
insert into Countries (Descripcion,Predeterminado) values ('MAYOTTE',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAHARA OCCIDENTAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS DE AFRICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CANADA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ESTADOS UNIDOS DE AMERICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MEXICO',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAN PEDRO Y MIQUELON ',0);	
insert into Countries (Descripcion,Predeterminado) values ('GROENLANDIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE',0);	
insert into Countries (Descripcion,Predeterminado) values ('ANTIGUA Y BARBUDA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BAHAMAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('BARBADOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('BELICE',0);	
insert into Countries (Descripcion,Predeterminado) values ('COSTA RICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CUBA',0);	
insert into Countries (Descripcion,Predeterminado) values ('DOMINICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('EL SALVADOR',0);	
insert into Countries (Descripcion,Predeterminado) values ('GRANADA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUATEMALA',0);	
insert into Countries (Descripcion,Predeterminado) values ('HAITI',0);	
insert into Countries (Descripcion,Predeterminado) values ('HONDURAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('JAMAICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('NICARAGUA',0);	
insert into Countries (Descripcion,Predeterminado) values ('PANAMA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAN VICENTE Y LAS GRANADINAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('REPUBLICA DOMINICANA',0);	
insert into Countries (Descripcion,Predeterminado) values ('TRINIDAD Y TOBAGO',0);	
insert into Countries (Descripcion,Predeterminado) values ('SANTA LUCIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAN CRISTOBAL Y NIEVES',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS CAIMÁN',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS TURCAS Y CAICOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS VÍRGENES DE LOS ESTADOS UNIDOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUADALUPE',0);	
insert into Countries (Descripcion,Predeterminado) values ('ANTILLAS HOLANDESAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAN MARTIN (PARTE FRANCESA)',0);	
insert into Countries (Descripcion,Predeterminado) values ('ARUBA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MONTSERRAT',0);	
insert into Countries (Descripcion,Predeterminado) values ('ANGUILLA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAN BARTOLOME',0);	
insert into Countries (Descripcion,Predeterminado) values ('MARTINICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('PUERTO RICO',0);	
insert into Countries (Descripcion,Predeterminado) values ('BERMUDAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS VIRGENES BRITANICAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('ARGENTINA',1);	
insert into Countries (Descripcion,Predeterminado) values ('BOLIVIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('BRASIL',0);	
insert into Countries (Descripcion,Predeterminado) values ('COLOMBIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CHILE',0);	
insert into Countries (Descripcion,Predeterminado) values ('ECUADOR',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUYANA',0);	
insert into Countries (Descripcion,Predeterminado) values ('PARAGUAY',0);	
insert into Countries (Descripcion,Predeterminado) values ('PERU',0);	
insert into Countries (Descripcion,Predeterminado) values ('SURINAM',0);	
insert into Countries (Descripcion,Predeterminado) values ('URUGUAY',0);	
insert into Countries (Descripcion,Predeterminado) values ('VENEZUELA',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUAYANA FRANCESA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS MALVINAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS  DE SUDAMERICA',0);	
insert into Countries (Descripcion,Predeterminado) values ('AFGANISTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('ARABIA SAUDI',0);	
insert into Countries (Descripcion,Predeterminado) values ('BAHREIN',0);	
insert into Countries (Descripcion,Predeterminado) values ('BANGLADESH',0);	
insert into Countries (Descripcion,Predeterminado) values ('MYANMAR',0);	
insert into Countries (Descripcion,Predeterminado) values ('CHINA',0);	
insert into Countries (Descripcion,Predeterminado) values ('EMIRATOS ARABES UNIDOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('FILIPINAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('INDIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('INDONESIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('IRAQ',0);	
insert into Countries (Descripcion,Predeterminado) values ('IRAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISRAEL',0);	
insert into Countries (Descripcion,Predeterminado) values ('JAPON',0);	
insert into Countries (Descripcion,Predeterminado) values ('JORDANIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('CAMBOYA',0);	
insert into Countries (Descripcion,Predeterminado) values ('KUWAIT',0);	
insert into Countries (Descripcion,Predeterminado) values ('LAOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('LIBANO',0);	
insert into Countries (Descripcion,Predeterminado) values ('MALASIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('MALDIVAS',0);	
insert into Countries (Descripcion,Predeterminado) values ('MONGOLIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('NEPAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('OMAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('PAKISTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('QATAR',0);	
insert into Countries (Descripcion,Predeterminado) values ('COREA',0);	
insert into Countries (Descripcion,Predeterminado) values ('COREA DEL NORTE ',0);	
insert into Countries (Descripcion,Predeterminado) values ('SINGAPUR',0);	
insert into Countries (Descripcion,Predeterminado) values ('SIRIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SRI LANKA',0);	
insert into Countries (Descripcion,Predeterminado) values ('TAILANDIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('VIETNAM',0);	
insert into Countries (Descripcion,Predeterminado) values ('BRUNEI',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS MARSHALL',0);	
insert into Countries (Descripcion,Predeterminado) values ('YEMEN',0);	
insert into Countries (Descripcion,Predeterminado) values ('AZERBAIYAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('KAZAJSTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('KIRGUISTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('TADYIKISTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('TURKMENISTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('UZBEKISTAN',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS MARIANAS DEL NORTE',0);	
insert into Countries (Descripcion,Predeterminado) values ('PALESTINA',0);	
insert into Countries (Descripcion,Predeterminado) values ('HONG KONG',0);	
insert into Countries (Descripcion,Predeterminado) values ('BHUTÁN',0);	
insert into Countries (Descripcion,Predeterminado) values ('GUAM',0);	
insert into Countries (Descripcion,Predeterminado) values ('MACAO',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS DE ASIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('AUSTRALIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('FIJI',0);	
insert into Countries (Descripcion,Predeterminado) values ('NUEVA ZELANDA',0);	
insert into Countries (Descripcion,Predeterminado) values ('PAPUA NUEVA GUINEA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS SALOMON',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAMOA',0);	
insert into Countries (Descripcion,Predeterminado) values ('TONGA',0);	
insert into Countries (Descripcion,Predeterminado) values ('VANUATU',0);	
insert into Countries (Descripcion,Predeterminado) values ('MICRONESIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('TUVALU',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS COOK',0);	
insert into Countries (Descripcion,Predeterminado) values ('NAURU',0);	
insert into Countries (Descripcion,Predeterminado) values ('PALAOS',0);	
insert into Countries (Descripcion,Predeterminado) values ('TIMOR ORIENTAL',0);	
insert into Countries (Descripcion,Predeterminado) values ('POLINESIA FRANCESA',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLA NORFOLK',0);	
insert into Countries (Descripcion,Predeterminado) values ('KIRIBATI',0);	
insert into Countries (Descripcion,Predeterminado) values ('NIUE',0);	
insert into Countries (Descripcion,Predeterminado) values ('ISLAS PITCAIRN',0);	
insert into Countries (Descripcion,Predeterminado) values ('TOKELAU',0);	
insert into Countries (Descripcion,Predeterminado) values ('NUEVA CALEDONIA',0);	
insert into Countries (Descripcion,Predeterminado) values ('WALLIS Y FORTUNA',0);	
insert into Countries (Descripcion,Predeterminado) values ('SAMOA AMERICANA',0);	
insert into Countries (Descripcion,Predeterminado) values ('OTROS PAISES O TERRITORIOS DE OCEANIA',0);	
